services:
  postgres:
    container_name: medicaldb
    image: postgres:16.9
    environment:
      POSTGRES_DB: "medical"
      POSTGRES_USER: "alljay"
      POSTGRES_PASSWORD: "4321"
    volumes:
      - "medical_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres -d db"]
        interval: 5s      
        timeout: 5s       
        retries: 10      
        start_period: 5s 
    networks:
      - dev
  
  medbackend:
    container_name: backend
    image: ${DOCKER_REGISTRY-}medapi
    build:
      context: ./backend
      dockerfile: MedicalHistory.API/Dockerfile
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - dev

volumes:
  medical_data:

networks:
  dev:
    driver: bridge